import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import Navbar from "@/components/navbar/navbar";
import "material-symbols/outlined.css";
import { Box, Flex } from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html suppressHydrationWarning>
      {/* Apply the font variable to the body */}
      <body className={`${jetbrains.className}`}>
        <Provider>
          <Flex direction={"column"} height={"100vh"}>
            <Navbar />
            <Box flex={"1"}>{children}</Box> {/* This is where the main content will be rendered, it provides a space without disrupting the navbar. */}
          </Flex>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
